# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        MainWindow.resize(874, 490)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.verticalFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.verticalFrame.sizePolicy().hasHeightForWidth()
        )
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalFrame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.verticalFrame.setLineWidth(0)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxLiveInfo = QtWidgets.QGroupBox(parent=self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBoxLiveInfo.sizePolicy().hasHeightForWidth()
        )
        self.groupBoxLiveInfo.setSizePolicy(sizePolicy)
        self.groupBoxLiveInfo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBoxLiveInfo.setObjectName("groupBoxLiveInfo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxLiveInfo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelCurrentState = QtWidgets.QLabel(parent=self.groupBoxLiveInfo)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelCurrentState.sizePolicy().hasHeightForWidth()
        )
        self.labelCurrentState.setSizePolicy(sizePolicy)
        self.labelCurrentState.setObjectName("labelCurrentState")
        self.verticalLayout.addWidget(self.labelCurrentState)
        self.lineEditCurrentState = QtWidgets.QLineEdit(parent=self.groupBoxLiveInfo)
        self.lineEditCurrentState.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEditCurrentState.sizePolicy().hasHeightForWidth()
        )
        self.lineEditCurrentState.setSizePolicy(sizePolicy)
        self.lineEditCurrentState.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditCurrentState.setMouseTracking(False)
        self.lineEditCurrentState.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEditCurrentState.setAcceptDrops(False)
        self.lineEditCurrentState.setFrame(True)
        self.lineEditCurrentState.setReadOnly(True)
        self.lineEditCurrentState.setPlaceholderText("")
        self.lineEditCurrentState.setClearButtonEnabled(False)
        self.lineEditCurrentState.setObjectName("lineEditCurrentState")
        self.verticalLayout.addWidget(self.lineEditCurrentState)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            10,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.verticalLayout.addItem(spacerItem)
        self.labelPreviousState = QtWidgets.QLabel(parent=self.groupBoxLiveInfo)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelPreviousState.sizePolicy().hasHeightForWidth()
        )
        self.labelPreviousState.setSizePolicy(sizePolicy)
        self.labelPreviousState.setObjectName("labelPreviousState")
        self.verticalLayout.addWidget(self.labelPreviousState)
        self.lineEditPreviousState = QtWidgets.QLineEdit(parent=self.groupBoxLiveInfo)
        self.lineEditPreviousState.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEditPreviousState.sizePolicy().hasHeightForWidth()
        )
        self.lineEditPreviousState.setSizePolicy(sizePolicy)
        self.lineEditPreviousState.setMouseTracking(False)
        self.lineEditPreviousState.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEditPreviousState.setAcceptDrops(False)
        self.lineEditPreviousState.setFrame(True)
        self.lineEditPreviousState.setReadOnly(True)
        self.lineEditPreviousState.setPlaceholderText("")
        self.lineEditPreviousState.setClearButtonEnabled(False)
        self.lineEditPreviousState.setObjectName("lineEditPreviousState")
        self.verticalLayout.addWidget(self.lineEditPreviousState)
        spacerItem1 = QtWidgets.QSpacerItem(
            20,
            10,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.verticalLayout.addItem(spacerItem1)
        self.labelLastEvent = QtWidgets.QLabel(parent=self.groupBoxLiveInfo)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelLastEvent.sizePolicy().hasHeightForWidth()
        )
        self.labelLastEvent.setSizePolicy(sizePolicy)
        self.labelLastEvent.setObjectName("labelLastEvent")
        self.verticalLayout.addWidget(self.labelLastEvent)
        self.lineEditLastEvent = QtWidgets.QLineEdit(parent=self.groupBoxLiveInfo)
        self.lineEditLastEvent.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEditLastEvent.sizePolicy().hasHeightForWidth()
        )
        self.lineEditLastEvent.setSizePolicy(sizePolicy)
        self.lineEditLastEvent.setMouseTracking(False)
        self.lineEditLastEvent.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEditLastEvent.setAcceptDrops(False)
        self.lineEditLastEvent.setFrame(True)
        self.lineEditLastEvent.setReadOnly(True)
        self.lineEditLastEvent.setPlaceholderText("")
        self.lineEditLastEvent.setClearButtonEnabled(False)
        self.lineEditLastEvent.setObjectName("lineEditLastEvent")
        self.verticalLayout.addWidget(self.lineEditLastEvent)
        spacerItem2 = QtWidgets.QSpacerItem(
            20,
            10,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.verticalLayout.addItem(spacerItem2)
        self.labelSessionTime = QtWidgets.QLabel(parent=self.groupBoxLiveInfo)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelSessionTime.sizePolicy().hasHeightForWidth()
        )
        self.labelSessionTime.setSizePolicy(sizePolicy)
        self.labelSessionTime.setObjectName("labelSessionTime")
        self.verticalLayout.addWidget(self.labelSessionTime)
        self.lineEditSessionTime = QtWidgets.QLineEdit(parent=self.groupBoxLiveInfo)
        self.lineEditSessionTime.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEditSessionTime.sizePolicy().hasHeightForWidth()
        )
        self.lineEditSessionTime.setSizePolicy(sizePolicy)
        self.lineEditSessionTime.setMouseTracking(False)
        self.lineEditSessionTime.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEditSessionTime.setAcceptDrops(False)
        self.lineEditSessionTime.setText("")
        self.lineEditSessionTime.setFrame(True)
        self.lineEditSessionTime.setReadOnly(True)
        self.lineEditSessionTime.setPlaceholderText("")
        self.lineEditSessionTime.setClearButtonEnabled(False)
        self.lineEditSessionTime.setObjectName("lineEditSessionTime")
        self.verticalLayout.addWidget(self.lineEditSessionTime)
        spacerItem3 = QtWidgets.QSpacerItem(
            20,
            10,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.verticalLayout.addItem(spacerItem3)
        self.labelPort = QtWidgets.QLabel(parent=self.groupBoxLiveInfo)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPort.sizePolicy().hasHeightForWidth())
        self.labelPort.setSizePolicy(sizePolicy)
        self.labelPort.setObjectName("labelPort")
        self.verticalLayout.addWidget(self.labelPort)
        self.lineEditPort = QtWidgets.QLineEdit(parent=self.groupBoxLiveInfo)
        self.lineEditPort.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPort.sizePolicy().hasHeightForWidth())
        self.lineEditPort.setSizePolicy(sizePolicy)
        self.lineEditPort.setMouseTracking(False)
        self.lineEditPort.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEditPort.setAcceptDrops(False)
        self.lineEditPort.setFrame(True)
        self.lineEditPort.setReadOnly(True)
        self.lineEditPort.setPlaceholderText("")
        self.lineEditPort.setClearButtonEnabled(False)
        self.lineEditPort.setObjectName("lineEditPort")
        self.verticalLayout.addWidget(self.lineEditPort)
        self.verticalLayout_2.addWidget(self.groupBoxLiveInfo)
        spacerItem4 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_2.addItem(spacerItem4)
        self.labelVersion = QtWidgets.QLabel(parent=self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVersion.sizePolicy().hasHeightForWidth())
        self.labelVersion.setSizePolicy(sizePolicy)
        self.labelVersion.setMinimumSize(QtCore.QSize(0, 0))
        self.labelVersion.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelVersion.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelVersion.setObjectName("labelVersion")
        self.verticalLayout_2.addWidget(self.labelVersion)
        self.horizontalLayout.addWidget(self.verticalFrame)
        self.groupBoxManualOverride = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBoxManualOverride.sizePolicy().hasHeightForWidth()
        )
        self.groupBoxManualOverride.setSizePolicy(sizePolicy)
        self.groupBoxManualOverride.setMinimumSize(QtCore.QSize(550, 450))
        self.groupBoxManualOverride.setStyleSheet("")
        self.groupBoxManualOverride.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.groupBoxManualOverride.setFlat(True)
        self.groupBoxManualOverride.setObjectName("groupBoxManualOverride")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxManualOverride)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.groupBoxManualOverride)
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.groupBoxManualOverride)
        self.verticalFrame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.verticalFrame_2.sizePolicy().hasHeightForWidth()
        )
        self.verticalFrame_2.setSizePolicy(sizePolicy)
        self.verticalFrame_2.setMinimumSize(QtCore.QSize(150, 0))
        self.verticalFrame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.verticalFrame_2.setLineWidth(0)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_4.addItem(spacerItem5)
        self.groupBox = QtWidgets.QGroupBox(parent=self.verticalFrame_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.verticalFrame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bpod Console"))
        self.groupBoxLiveInfo.setTitle(_translate("MainWindow", "Live Info"))
        self.labelCurrentState.setText(_translate("MainWindow", "Current State"))
        self.labelPreviousState.setText(_translate("MainWindow", "Previous State"))
        self.labelLastEvent.setText(_translate("MainWindow", "Last Event"))
        self.labelSessionTime.setText(_translate("MainWindow", "Session Time"))
        self.labelPort.setText(_translate("MainWindow", "Port"))
        self.labelVersion.setText(_translate("MainWindow", "bpod v1.0.0"))
        self.groupBoxManualOverride.setTitle(
            _translate("MainWindow", "Manual Override")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("MainWindow", "State Machine")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Stepper_1")
        )
        self.groupBox.setTitle(_translate("MainWindow", "Session"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
